site_name: card_games_app
site_url: https://coperta4869.github.io/streamlit-practice/
theme:
  name: material
nav:
  - Home: index.md
  - High_and_Low: High_and_Low.md
repo_url: https://github.com/coperta4869/streamlit-practice

extra:
  version:
    provider: mike